---
gighive_enable_installation_tracking: true
gighive_installation_tracking_endpoint: "https://telemetry.gighive.app"
gighive_enable_installation_tracking_debug: false
gighive_installation_tracking_timeout_seconds: 3
gighive_install_channel: "full"
gighive_install_method: "virtualbox"
app_flavor: "gighive"
